FROM tomcat:8.5.100-jdk11-temurin

# Install JMX exporter
RUN mkdir -p /app && \
    wget -O /app/jmx_prometheus_javaagent.jar https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/1.0.1/jmx_prometheus_javaagent-1.0.1.jar
COPY ./jmx_exporter_config.yml /app/jmx_exporter_config.yml

# Set JVM options to include JMX exporter
ENV JAVA_OPTS="-javaagent:/app/jmx_prometheus_javaagent.jar=1234:/app/jmx_exporter_config.yml"

CMD ["catalina.sh", "run"]
